export const SAMPLE_INCREASE = 'SAMPLE_INCREASE';
export const SAMPLE_DECREASE = 'SAMPLE_DECREASE';
export const FETCH_SAMPLES = 'FETCH_SAMPLES';
export const GET_CLASS = 'GET_CLASS';
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const SET_CLASSES = 'SET_CLASSES';
export const FETCH_CLASSES = 'FETCH_CLASSES';

export const FETCH_AVAILABLE_VOLUNTEERS = 'FETCH_AVAILABLE_VOLUNTEERS';
export const RECIEVE_RANDOMIZED_VOLUNTEERS = 'RECIEVE_RANDOMIZED_VOLUNTEERS';
export const SET_LIST_OF_STUDENTS = 'SET_LIST_OF_STUDENTS';
export const SUCCESS = 'SUCCESS';

export const SET_VOLUNTEERS = 'SET_VOLUNTEERS';
export const MODIFY_TAGS = 'MODIFY_TAGS';
export const MODIFY_STUDENTS = 'MODIFY_STUDENTS';

export const SET_STUDENT = 'SET_STUDENT';
